version: '3'
services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_HOST: localhost
            MYSQL_DATABASE: mydb
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - '3306:3306'
        expose:
            - 3306
        volumes:
            - /data/mysql:/var/lib/mysql
        restart: unless-stopped
    web:
        build:
            context: .
            dockerfile: web/Dockerfile
        volumes:
            - ./:/web
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: development
            PORT: 3000
        links:
            - mysql:mysql
        depends_on:
            - mysql
        expose:
            - 3000
